name: Daily Tenzing Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        pip install pandas
      # This will install pandas if necessary

    - name: Run tenzing.py
      run: python tenzing.py

    - name: Commit and push changes
      run: |
        git config --global user.email "lukas.wallrich@gmail.com"
        git config --global user.name "Lukas Wallrich"
        git add tenzing.md
        git commit -m "Daily update"
        git push
